version: '3.1'
services:
  odoo:
    image: odoo:17
    depends_on:
      - db_custom
    restart: always
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - web-odoo:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
      - LOG_LEVEL=debug
    secrets:
      - postgresql_password

  db_custom:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db-odoo:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password
  flask:
      build: ./flask
      ports:
        - "5000:5000"
      restart: always

volumes:
  web-odoo:
  db-odoo:

secrets:
  postgresql_password:
    file: odoo_pg_pass
